services:
  - type: web
    name: curalink-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://curalink_user:Atif12345@mark-1.qbfcybi.mongodb.net/curalink?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: curalink_jwt_secret_change_this_in_production_for_real
      - key: OPENAI_API_KEY
        value: sk-proj-6rY-zX_aSSZ12oYSu_eNvdykGti3P1-iZVd7q0uyCHVeL-6-bv5oAI_zPaYub04OFDC_ImuX61WDT3R1bkF_l20wYXtoizDGSCEEDP_EKoa/SNhP2Rfi_Awvfbo
      - key: OPENAI_MODEL
        value: gpt-4o
